In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import gmaps

In [2]:
#read file
zip_tract = "Resources/ziptract2010.csv"
tract_us = "Resources/2009-2013_American_Community_Survey_Basic_Census_Tract_Data.csv"

In [3]:
# Read the data 
zip_tract = pd.read_csv(zip_tract)
tract_us = pd.read_csv(tract_us)

In [10]:
zip_tract
# tract_us

              TRACT    ZIP
0       36103158607    501
1       36103158607    544
2       72001956300    601
3       72001956600    601
4       72001956700    601
...             ...    ...
145624   2201000200  99925
145625   2201000400  99926
145626   2201000100  99927
145627   2130000100  99928
145628   2280000300  99929

[145629 rows x 2 columns]

In [6]:
tract_us = tract_us.rename(columns={'STFID Number':'TRACT'})
tract_us

,Island Number,Census Tract,KCMO Portion or Not,STFID Label,TRACT,County,X Centroid,Y Centroid,Population,Age Under 5 Years,...,% Units Built 1990 to 1999,% Units Built 2000 to 2010,% Units Built 2011 to 2013,Median Home Value,Owner-Occupied Units,Renter-Occupied Units,% Owner-Occupied Units,% Renter-Occupied Units,Vacant Units,% Vacant Units
0,1,601.00,KCMO,29037060100,29037060100,Cass,2771674,971518,109,3,...,37.3,0.0,0.0,37500.0,0,24,0.0,100.0,0,0.0
1,2,202.01,KCMO,29047020201,29047020201,Clay,2769244,1092055,4695,214,...,12.8,4.2,2.4,93946.0,940,1222,43.5,56.5,344,13.7
2,3,202.02,KCMO,29047020202,29047020202,Clay,2761381,1095073,3232,110,...,11.9,22.1,0.0,212106.0,1239,231,84.3,15.7,126,7.9
3,4,203.00,KCMO,29047020300,29047020300,Clay,2768859,1100172,5308,487,...,5.6,6.8,0.0,133997.0,1178,1040,53.1,46.9,281,11.2
4,5,204.00,KCMO,29047020400,29047020400,Clay,2772599,1096332,2480,140,...,3.1,0.0,0.0,113235.0,550,495,52.6,47.4,131,11.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
569,575,307.00,Not KCMO,29165030700,29165030700,Platte,2663297,1196584,3555,186,...,8.8,17.3,0.0,179928.0,959,362,72.6,27.4,128,8.8
570,576,800.00,Not KCMO,29177080000,29177080000,Ray,2903413,1178703,7425,430,...,22.1,14.3,0.3,146809.0,2320,353,86.8,13.2,304,10.2
571,577,801.00,Not KCMO,29177080100,29177080100,Ray,2958588,1153897,3683,181,...,12.6,14.4,0.0,116366.0,1057,188,84.9,15.1,211,14.5
572,578,802.00,Not KCMO,29177080200,29177080200,Ray,2937622,1133338,6282,411,...,9.9,11.4,1.0,104940.0,1568,945,62.4,37.6,428,14.6
573,579,803.00,Not KCMO,29177080300,29177080300,Ray,2905415,1126000,5900,379,...,16.0,11.6,0.0,122808.0,1873,431,81.3,18.7,279,10.8

In [8]:
merged_df= zip_tract.merge(tract_us, how='right', on= 'TRACT')
merged_df

,TRACT,ZIP,Island Number,Census Tract,KCMO Portion or Not,STFID Label,County,X Centroid,Y Centroid,Population,...,% Units Built 1990 to 1999,% Units Built 2000 to 2010,% Units Built 2011 to 2013,Median Home Value,Owner-Occupied Units,Renter-Occupied Units,% Owner-Occupied Units,% Renter-Occupied Units,Vacant Units,% Vacant Units
0,29107090300,64001.0,557,903.00,Not KCMO,29107090300,Lafayette,3046771,1105272,1497,...,13.1,4.8,0.2,88085.0,378,188,66.8,33.2,115,16.9
1,29107090300,64021.0,557,903.00,Not KCMO,29107090300,Lafayette,3046771,1105272,1497,...,13.1,4.8,0.2,88085.0,378,188,66.8,33.2,115,16.9
2,29107090300,64022.0,557,903.00,Not KCMO,29107090300,Lafayette,3046771,1105272,1497,...,13.1,4.8,0.2,88085.0,378,188,66.8,33.2,115,16.9
3,29107090300,64096.0,557,903.00,Not KCMO,29107090300,Lafayette,3046771,1105272,1497,...,13.1,4.8,0.2,88085.0,378,188,66.8,33.2,115,16.9
4,29107090400,64001.0,558,904.00,Not KCMO,29107090400,Lafayette,3018889,1050064,6793,...,8.1,7.1,0.1,101918.0,1948,871,69.1,30.9,268,8.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1093,29095018500,NaN,549,185.00,Not KCMO,29095018500,Jackson,2832698,1026551,3403,...,54.0,30.5,1.8,236477.0,1101,132,89.3,10.7,36,2.8
1094,29095018600,NaN,550,186.00,Not KCMO,29095018600,Jackson,2831782,1009406,2948,...,37.7,13.8,0.6,167938.0,1029,45,95.8,4.2,30,2.7
1095,29095019300,NaN,551,193.00,Not KCMO,29095019300,Jackson,2839163,1039790,5932,...,24.0,20.9,0.0,150665.0,1898,472,80.1,19.9,214,8.3
1096,29107090601,NaN,560,906.01,Not KCMO,29107090601,Lafayette,2944985,1025538,5798,...,17.0,14.0,0.0,118168.0,1581,669,70.3,29.7,292,11.5
1097,29107090602,NaN,561,906.02,Not KCMO,29107090602,Lafayette,2912758,1018432,3819,...,29.9,14.7,0.0,164316.0,1407,92,93.9,6.1,176,10.5

In [9]:
merged_df= merged_df.dropna(how='any')
merged_df

,TRACT,ZIP,Island Number,Census Tract,KCMO Portion or Not,STFID Label,County,X Centroid,Y Centroid,Population,...,% Units Built 1990 to 1999,% Units Built 2000 to 2010,% Units Built 2011 to 2013,Median Home Value,Owner-Occupied Units,Renter-Occupied Units,% Owner-Occupied Units,% Renter-Occupied Units,Vacant Units,% Vacant Units
0,29107090300,64001.0,557,903.00,Not KCMO,29107090300,Lafayette,3046771,1105272,1497,...,13.1,4.8,0.2,88085.0,378,188,66.8,33.2,115,16.9
1,29107090300,64021.0,557,903.00,Not KCMO,29107090300,Lafayette,3046771,1105272,1497,...,13.1,4.8,0.2,88085.0,378,188,66.8,33.2,115,16.9
2,29107090300,64022.0,557,903.00,Not KCMO,29107090300,Lafayette,3046771,1105272,1497,...,13.1,4.8,0.2,88085.0,378,188,66.8,33.2,115,16.9
3,29107090300,64096.0,557,903.00,Not KCMO,29107090300,Lafayette,3046771,1105272,1497,...,13.1,4.8,0.2,88085.0,378,188,66.8,33.2,115,16.9
4,29107090400,64001.0,558,904.00,Not KCMO,29107090400,Lafayette,3018889,1050064,6793,...,8.1,7.1,0.1,101918.0,1948,871,69.1,30.9,268,8.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,20091052603,66218.0,235,526.03,Not KCMO,20091052603,Johnson,2694530,1038993,16897,...,38.8,43.9,0.4,217857.0,4759,499,90.5,9.5,45,0.8
939,20091052603,66226.0,235,526.03,Not KCMO,20091052603,Johnson,2694530,1038993,16897,...,38.8,43.9,0.4,217857.0,4759,499,90.5,9.5,45,0.8
940,20091052603,66227.0,235,526.03,Not KCMO,20091052603,Johnson,2694530,1038993,16897,...,38.8,43.9,0.4,217857.0,4759,499,90.5,9.5,45,0.8
941,20091052415,66219.0,226,524.15,Not KCMO,20091052415,Johnson,2712353,1018561,3180,...,17.9,12.1,0.0,227692.0,628,738,46.0,54.0,34,2.4
942,20091053409,66224.0,271,534.09,Not KCMO,20091053409,Johnson,2752090,986698,3455,...,40.5,32.9,0.0,420370.0,1027,214,82.8,17.2,37,2.9

In [15]:
merged_df.count

<bound method DataFrame.count of            TRACT      ZIP  Island Number  Census Tract KCMO Portion or Not  \
0    29107090300  64001.0            557        903.00            Not KCMO
1    29107090300  64021.0            557        903.00            Not KCMO
2    29107090300  64022.0            557        903.00            Not KCMO
3    29107090300  64096.0            557        903.00            Not KCMO
4    29107090400  64001.0            558        904.00            Not KCMO
..           ...      ...            ...           ...                 ...
938  20091052603  66218.0            235        526.03            Not KCMO
939  20091052603  66226.0            235        526.03            Not KCMO
940  20091052603  66227.0            235        526.03            Not KCMO
941  20091052415  66219.0            226        524.15            Not KCMO
942  20091053409  66224.0            271        534.09            Not KCMO

     STFID Label     County  X Centroid  Y Centroid  Population  ...  \
0    29107090300  Lafayette     3046771     1105272        1497  ...
1    29107090300  Lafayette     3046771     1105272        1497  ...
2    29107090300  Lafayette     3046771     1105272        1497  ...
3    29107090300  Lafayette     3046771     1105272        1497  ...
4    29107090400  Lafayette     3018889     1050064        6793  ...
..           ...        ...         ...         ...         ...  ...
938  20091052603    Johnson     2694530     1038993       16897  ...
939  20091052603    Johnson     2694530     1038993       16897  ...
940  20091052603    Johnson     2694530     1038993       16897  ...
941  20091052415    Johnson     2712353     1018561        3180  ...
942  20091053409    Johnson     2752090      986698        3455  ...

     % Units Built 1990 to 1999  % Units Built 2000 to 2010  \
0                          13.1                         4.8
1                          13.1                         4.8
2                          13.1                         4.8
3                          13.1                         4.8
4                           8.1                         7.1
..                          ...                         ...
938                        38.8                        43.9
939                        38.8                        43.9
940                        38.8                        43.9
941                        17.9                        12.1
942                        40.5                        32.9

     % Units Built 2011 to 2013  Median Home Value  Owner-Occupied Units  \
0                           0.2            88085.0                   378
1                           0.2            88085.0                   378
2                           0.2            88085.0                   378
3                           0.2            88085.0                   378
4                           0.1           101918.0                  1948
..                          ...                ...                   ...
938                         0.4           217857.0                  4759
939                         0.4           217857.0                  4759
940                         0.4           217857.0                  4759
941                         0.0           227692.0                   628
942                         0.0           420370.0                  1027

     Renter-Occupied Units  % Owner-Occupied Units  % Renter-Occupied Units  \
0                      188                    66.8                     33.2
1                      188                    66.8                     33.2
2                      188                    66.8                     33.2
3                      188                    66.8                     33.2
4                      871                    69.1                     30.9
..                     ...                     ...                      ...
938                    499                    90.5                      9.5
939                    499                    90.5                      9.5
940                    499                    90.5                      9.5
941                    738                    46.0                     54.0
942                    214                    82.8                     17.2

     Vacant Units  % Vacant Units
0             115            16.9
1             115            16.9
2             115            16.9
3             115            16.9
4             268             8.7
..            ...             ...
938            45             0.8
939            45             0.8
940            45             0.8
941            34             2.4
942            37             2.9

[909 rows x 117 columns]>

In [16]:
merged_df.to_csv("TRACT-STFID-data.csv")